# Generated by Django 4.2.5 on 2023-09-14 07:24

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('main', '0001_initial')]

    operations = [
        migrations.RenameModel(old_name='Restaurant', new_name='Textiles'),
        migrations.AlterModelOptions(
            name='textiles', options={'ordering': ('name',), 'verbose_name_plural': 'Textiles'}
        ),
    ]
