# Generated by Django 4.2.4 on 2023-09-06 23:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('main', '0001_initial')]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='restaurant',
            field=models.ForeignKey(
                default='3d44aba9-e11c-4c50-aa35-eafc7e6394e0',
                on_delete=django.db.models.deletion.CASCADE,
                to='main.restaurant',
            ),
            preserve_default=False,
        )
    ]
