# Generated by Django 4.2.5 on 2023-09-18 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_option_org_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='option',
            name='org_price',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='cut this price', max_digits=10, null=True),
        ),
    ]
