# Generated by Django 4.2.4 on 2023-09-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('main', '0002_cartitem_restaurant')]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='phone',
            field=models.CharField(help_text='Phone number with country code', max_length=200),
        )
    ]
