# Generated by Django 4.2.5 on 2023-09-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('main', '0003_option_org_price')]

    operations = [
        migrations.AddField(model_name='textiles', name='location_url', field=models.URLField(blank=True, null=True)),
        migrations.AlterField(model_name='cartitem', name='quantity', field=models.PositiveIntegerField(default=0)),
    ]
