# Generated by Django 4.2.4 on 2023-09-07 10:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [migrations.swappable_dependency(settings.AUTH_USER_MODEL), ('main', '0003_alter_restaurant_phone')]

    operations = [
        migrations.AddField(
            model_name='cataloguead', name='display_in', field=models.ManyToManyField(blank=True, to='main.restaurant')
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                (
                    'id',
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='State Name')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='creator_%(class)s_objects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={'abstract': False},
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                (
                    'id',
                    models.UUIDField(blank=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
                ),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=50, verbose_name='State Name')),
                (
                    'created_by',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='creator_%(class)s_objects',
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ('state', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.state')),
            ],
            options={'abstract': False},
        ),
        migrations.AddField(
            model_name='restaurant',
            name='district',
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.district'
            ),
        ),
    ]
