# Generated by Django 4.2.4 on 2023-09-07 15:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [('main', '0004_cataloguead_display_in_state_district_and_more')]

    operations = [
        migrations.AddField(
            model_name='restaurant', name='feature_description', field=models.TextField(blank=True, null=True)
        ),
        migrations.AddField(
            model_name='restaurant',
            name='feature_image',
            field=models.ImageField(default=1, upload_to=None),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification', models.TextField()),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='CheckoutAd',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='checkout/ads/')),
                ('display_upto', models.DateField()),
                ('display_in', models.ManyToManyField(blank=True, to='main.restaurant')),
            ],
        ),
    ]
