# Generated by Django 4.2.4 on 2023-09-07 16:41

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [('main', '0005_restaurant_feature_description_and_more')]

    operations = [
        migrations.AlterModelOptions(
            name='option', options={'ordering': ('product', 'price'), 'verbose_name_plural': 'Options'}
        )
    ]
