# Generated by Django 4.2.4 on 2023-09-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [('main', '0006_alter_option_options')]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='feature_image',
            field=models.ImageField(upload_to='restaurant/feature_images/'),
        )
    ]
