# Generated by Django 4.2.4 on 2023-09-08 20:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [('main', '0007_alter_restaurant_feature_image')]

    operations = [
        migrations.RemoveField(model_name='productad', name='is_active'),
        migrations.AddField(model_name='product', name='display_foodtype', field=models.BooleanField(default=True)),
        migrations.AddField(
            model_name='productad', name='display_in', field=models.ManyToManyField(blank=True, to='main.restaurant')
        ),
        migrations.AddField(
            model_name='productad',
            name='display_upto',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
