# Generated by Django 4.2.5 on 2023-09-11 05:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_productad_is_active_product_display_foodtype_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='restaurant',
            options={'ordering': ('name',), 'verbose_name_plural': 'textiles'},
        ),
        migrations.RenameField(
            model_name='option',
            old_name='name',
            new_name='size',
        ),
    ]
