# Generated by Django 4.2.5 on 2023-09-11 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_alter_restaurant_options_rename_name_option_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='option',
            old_name='size',
            new_name='name',
        ),
    ]
