# Generated by Django 4.2.5 on 2023-09-11 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_size_option_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='display_foodtype',
        ),
    ]
