# Generated by Django 4.2.5 on 2023-09-11 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_remove_product_display_foodtype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='ingredients',
        ),
    ]
