# Generated by Django 4.2.5 on 2023-09-11 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_alter_banner_restaurant_alter_category_restaurant'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CheckoutAd',
        ),
    ]
