# Generated by Django 4.2.5 on 2023-09-11 09:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_delete_checkoutad'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
    ]
