# Generated by Django 4.2.5 on 2023-09-11 09:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_remove_product_price'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CartItem',
        ),
    ]
