# Generated by Django 4.2.5 on 2023-09-11 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_cartitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant', verbose_name='Textiles'),
        ),
        migrations.AlterField(
            model_name='notification',
            name='restaurant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.restaurant', verbose_name='Textiles'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='feature_image',
            field=models.ImageField(blank=True, null=True, upload_to='restaurant/feature_images/'),
        ),
    ]
