# Generated by Django 4.2.5 on 2023-09-11 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_alter_category_restaurant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_vegetarian',
        ),
    ]
