# Generated by Django 4.2.5 on 2023-09-11 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_product_is_vegetarian'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='is_vegetarian',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
