# Generated by Django 4.2.5 on 2023-09-11 12:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_alter_product_is_vegetarian'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='is_vegetarian',
        ),
    ]
